"""empty message

Revision ID: 63077dd35def
Revises: 
Create Date: 2020-06-06 20:05:22.845440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63077dd35def'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('idLanguage', sa.Integer(), nullable=False),
    sa.Column('condition', sa.String(length=2), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('isFoil', sa.String(), nullable=True),
    sa.Column('idArticle', sa.String(), nullable=True),
    sa.Column('comments', sa.String(length=200), nullable=True),
    sa.Column('img', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idProduct', 'name', 'idLanguage', 'condition', 'isFoil', name='_card_nondup_uc')
    )
    op.create_table('price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProduct', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['idProduct'], ['card.idProduct'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_timestamp'), 'price', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_timestamp'), table_name='price')
    op.drop_table('price')
    op.drop_table('card')
    # ### end Alembic commands ###
